# frozen_string_literal: true

source 'https://cdn.cocoapods.org/'

use_modular_headers!
platform :ios, '13.0'

project 'KanvasExample.xcodeproj'

target 'KanvasExample' do
  pod 'Kanvas', path: '../'
  pod 'CropViewController'

  target 'KanvasExampleTests' do
    inherit! :search_paths
    use_frameworks!
    pod 'iOSSnapshotTestCase', '8.0.0'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end

