source 'https://github.com/CocoaPods/Specs.git'

use_modular_headers!
platform :ios, '13.0'

project "KanvasExample.xcodeproj"

target 'KanvasExample' do
    pod 'Kanvas', :path => '../'
    
    target 'KanvasExampleTests' do
        inherit! :search_paths
	use_frameworks!
        pod 'iOSSnapshotTestCase', '8.0.0'
    end
end
