source 'https://github.com/CocoaPods/Specs.git'

use_modular_headers!
platform :ios, '13.0'

project "KanvasCameraExample.xcodeproj"

target 'KanvasCameraExample' do
    pod 'KanvasCamera', :path => '../'
    
    target 'KanvasCameraExampleTests' do
        inherit! :search_paths
        pod 'FBSnapshotTestCase', '2.1.4'
    end
end
