source 'https://cdn.cocoapods.org/'

use_modular_headers!
platform :ios, '12.0'

project "KanvasCameraExample.xcodeproj"

target 'KanvasCameraExample' do
    pod 'KanvasCamera', :path => '../'
    
    target 'KanvasCameraExampleTests' do
        inherit! :search_paths
        pod 'FBSnapshotTestCase', '2.1.4'
    end
end
