platform :ios, '11.0'
use_frameworks!

target 'KanvasCameraExample' do
	pod 'KanvasCamera', :path => '../'
end

target 'KanvasCameraExampleTests' do
    pod 'KanvasCamera', :path => '../'
    pod 'FBSnapshotTestCase', '2.1.4'
end
