platform :ios, '12.0'
use_frameworks!

target 'KanvasCameraExample' do
    pod 'KanvasCamera', :path => '../'
    pod 'TumblrTheme', :path => '../../TumblrTheme'
    pod 'SharedUI', :path => '../../SharedUI'
    pod 'Utils', :path => '../../Utils'
    pod 'ImageLoader', :path => '../../ImageLoader'
end

target 'KanvasCameraExampleTests' do
    pod 'KanvasCamera', :path => '../'
    pod 'FBSnapshotTestCase', '2.1.4'
end
